language: php

php:
  - '7.1'

before_script:
  - composer require satooshi/php-coveralls
  - composer install

script:
- mkdir -p build/logs
- ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
 
after_script:
- php vendor/bin/coveralls -v

notifications:
  email:
    on_success: never
  
  
