language: php

php:
  - '7.1'

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer require satooshi/php-coveralls:^2.0
  - travis_retry composer install

before_script:
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php ./vendor/bin/coveralls -v

notifications:
  email:
    on_success: never
